### PR TITLE
Adding $schema to the plugin.schema.json.

### LINKED ISSUE #1: Allow $schema in the plugin.json
Current `plugin.schema.json` doesn't have option to enter `$schema`. Allowing `$schema` will enhance IDEs to autocomplete and lint the `plugin.json` file. 

#### **With schema**: ( Autocomplete and Linting ) 

image
image
image
image

#### **Without schema**: ( No autocomplete, No Lint )

image
image

### PR DESCRIPTION
**Pull request by yesoreyeram**
Adding $schema property to the `plugin.schema.json` file. This will help IDEs to autocomplete and lint `plugin.json` file. Fixes #1

### CODE REVIEW

**Comment by yesoreyeram** [comment]
Eventually once this tool matures, `plugin.schema.json` should be moved to standard domain like `grafana.com` / [json schema store](https://www.schemastore.org/json/)

**Comment by marcusolsson** [comment]
Great idea! Though, the schema in this repository is simply a mirror of the [original schema](https://github.com/grafana/grafana/blob/master/docs/sources/developers/plugins/plugin.schema.json) in the Grafana repository.

Would you mind creating a pull request on the [grafana/grafana](https://github.com/grafana/grafana) repository instead? I think it's safe to group the schema suggestions into one PR, and keep the discussion there.

**Comment by yesoreyeram** [comment]
Thanks @marcusolsson. Created PR at [grafana/grafana](https://github.com/grafana/grafana/pull/27029). Only with "$schema" changes. Let's keep the discussion there on handling other schema changes. 

Feel free to close this PR and Issue as required.

Is there sync between these two schema definition? Just curious to understand.

**Comment by marcusolsson** [comment]
There's no sync yet. Ideally I'd like to remove the schema from this repository. Maybe download the schema from the grafana repository during the check or from https://www.schemastore.org/json/.

**Pull request closed without merging**
